name: Upload Benchmarks

on:
  push:
    branches:
      - main

jobs:
  upload_benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Use Node.js from nvmrc
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v4
        with:
          node-version-file: '.nvmrc'
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build benchmarks
        run: |
          pnpm run generate-typings
          pnpm run build-benchmarks

      - name: Copy benchmarks_generated.js
        run: |
          mkdir tmp
          cp test/bench/versions/benchmarks_generated.js tmp
          cp test/bench/versions/benchmarks_generated.js.map tmp

      - name: Upload to GitHub Pages (main)
        if: startsWith(github.ref, 'refs/heads/main')
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: tmp
          destination_dir: benchmarks/main
